name = "sale-eu-api"
main = "src/index.js"
compatibility_date = "2026-09-20"

[[d1_databases]]
binding = "DB"
database_name = "sale-eu"
database_id = "c5fa73a9-cf5e-4e4b-b225-3e2440b62b27"

[vars]
# Do not put your admin token here in production.
# Use: wrangler secret put ADMIN_TOKEN
